version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:8.0'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=db_zenblog
    networks:
      - app-tier
    ports:
      - 3310:3306