apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-order
spec:
  replicas: 2
  selector:
    matchLabels:
      component: service-order-pod
  template:
    metadata:
      labels:
        component: service-order-pod
    spec:
      containers:
        - name: service-order-ctn
          image: longdd90jp/aws-service-order
          ports:
          - containerPort: 8080
            name: rest-port
          - containerPort: 8085
            name: grpc-port
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name