apiVersion: v1
kind: Service
metadata:
  name: service-post
  labels:
    component: service-post
spec:
  type: ClusterIP
  selector:
    component: service-post-pod
  ports:
    - port: 8080
      protocol: TCP
      name: rest-port
      targetPort: 8080
    - port: 8085
      protocol: TCP
      name: grpc-port
      targetPort: 8085